### ISSUE TITLE
Question about understanding the output of cluster-cluster communication

### ISSUE THREAD

**Issue by dongyuanwu** [zcang/COMMOT#10]
Hi,

I just have one quick question about the output of `tl.cluster_communication_spatial_permutation()`. It provided both the communication score matrix and the communication p-value matrix. Since I found they were not symmetric matrices, I would like to check the meaning of the column name and row name: which one represents the sender clusters (of course, another should be the receiver)? I did not find the explanation in the tutorial, not sure if I missed something.

Thanks in advance!

**Comment by zcang** [comment]
Hi, sorry for the confusion, the rows (first index) represent senders and the columns (second index) represent receivers.
