### ISSUE TITLE
unable to install commot

### ISSUE THREAD

**Issue by ayusyarif** [zcang/COMMOT#2]
Dear Developer,

I made several attempts to install commit using jupyter and spyder. However, it kept giving me an error message. 

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]`
  
  `note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rvlib
  Running setup.py clean for rvlib
Failed to build rvlib
Installing collected packages: python-louvain, Levenshtein, rvlib, requests-futures, rasterio, quantecon, python-Levenshtein, python-igraph, pygsp, pot, pandas, leidenalg, inequality, fiona, deprecation, aws-requests-auth, rasterstats, pynndescent, mapclassify, libpysal, karateclub, geopandas, anndata, umap-learn, tobler, spreg, pointpats, momepy, esda, access, spvcm, spglm, spaghetti, scanpy, quilt3, giddy, spopt, splot, spint, segregation, mgwr, pysal, commot
  Running setup.py install for rvlib ... error
  error: subprocess-exited-with-error`
  
  `× Running setup.py install for rvlib did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running install
      /Users/ayuhutamisyarif/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-39
      creating build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      copying rvlib/univariate.py -> build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      copying rvlib/version.py -> build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      copying rvlib/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      copying rvlib/specials.py -> build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      running egg_info
      writing rvlib.egg-info/PKG-INFO
      writing dependency_links to rvlib.egg-info/dependency_links.txt
      writing requirements to rvlib.egg-info/requires.txt
      writing top-level names to rvlib.egg-info/top_level.txt
      reading manifest file 'rvlib.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'rvlib.egg-info/SOURCES.txt'
      copying rvlib/metadata.yaml -> build/lib.macosx-10.9-x86_64-cpython-39/rvlib
      running build_ext
      generating cffi module 'build/temp.macosx-10.9-x86_64-cpython-39/rvlib._rmath_ffi.c'
      creating build/temp.macosx-10.9-x86_64-cpython-39
      building 'rvlib._rmath_ffi' extension
      creating build/temp.macosx-10.9-x86_64-cpython-39/build
      creating build/temp.macosx-10.9-x86_64-cpython-39/build/temp.macosx-10.9-x86_64-cpython-39
      creating build/temp.macosx-10.9-x86_64-cpython-39/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ayuhutamisyarif/opt/anaconda3/include -arch x86_64 -I/Users/ayuhutamisyarif/opt/anaconda3/include -fPIC -O2 -isystem /Users/ayuhutamisyarif/opt/anaconda3/include -arch x86_64 -Isrc -Iinclude -I/Users/ayuhutamisyarif/opt/anaconda3/include/python3.9 -c build/temp.macosx-10.9-x86_64-cpython-39/rvlib._rmath_ffi.c -o build/temp.macosx-10.9-x86_64-cpython-39/build/temp.macosx-10.9-x86_64-cpython-39/rvlib._rmath_ffi.o -DMATHLIB_STANDALONE -std=c99
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]`
  
  `note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure`

`× Encountered error while trying to install package.
╰─> rvlib`

`note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

I am very new to python and have no idea about this error. Any advice would be so much appreciated

Best,
Ayu

**Comment by zcang** [comment]
Hi, does installing other packages like scanpy result in the same error? It seems xcrun is missing. I am not familiar with macOS but a search of the first line of the error message gives me this solution:  https://developer.apple.com/forums/thread/711512
