### ISSUE TITLE
Question about the COMMOT paper

### ISSUE THREAD

**Issue by LixinyuLiu** [zcang/COMMOT#21]
Hi, 

![WechatIMG2518](https://github.com/zcang/COMMOT/assets/43229475/251896f0-a8d0-4920-bb9e-aeab47560a2d)

I am reading the COMMOT paper and I came across a a few questions about the **Methods: spatial signalling direction.** 

1) what is the xi and xj representing? Are they the coordinates for spot i and j?
2) What does N function indicates?
3) V belongs to Rns x d, what is the d here?

Thank you in advance for you time and patience. I am looking forward to your reply. 

Best regards, 
Ema

**Comment by zcang** [comment]
Hello, 

$x_i$ and $x_j$ are the spatial coordinates of spots i and j. 
The function $N(x)$ is supposed to be simply normalizing the vector, i.e. $x/\|x\|$. (I don't know why it got displayed like that in the final version.)
d is the dimension of the ST data which is often 2.

Best,
Zixuan
