### ISSUE TITLE
How to set 'dis_thr ' correctly?

### ISSUE THREAD

**Issue by CenviaTZC** [zcang/COMMOT#4]
Hi ,
        When I use 'ct.tl.spatial_communication', I noticed that your description of ‘dis_thr’ in the tutorial is 'The threshold of spatial distance of signaling.', but I don't understand what the units of this number are, is it the number of cells? Or um?
        And how do I set an appropriate distance for my organization? According to the max area?

**Comment by zcang** [comment]
Hi, the distance threshold takes the same unit as the spatial coordinates stored in adata.obsm['spatial'].
