### ISSUE TITLE
About 'ct.pl.plot_cell_communication'

### ISSUE THREAD

**Issue by CenviaTZC** [zcang/COMMOT#5]
Hi, zcang,
  
I have another question.
    
When I want to use '**_ct.pl.plot_cell_communication_**' to plot '**_sender_**' and '**_receiver_**' on the same figure , I set '**_ax_**' and got the following error:
__
![image](https://user-images.githubusercontent.com/82918921/219298473-8fab73d0-1851-4eed-8fd2-abe23fc9303d.png)

I see that in function('**_plot_cell_signaling_**') ,  you use the  _**fig**_, but after I set **_ax_**, **_fig_** cannot be input from(**_'ct.pl.plot_cell_communication'_**)

![354bbac4d748aaa9d8f614518dc92e6](https://user-images.githubusercontent.com/82918921/219299432-88011d8a-5ed3-4cf8-ab05-f5c443c4659e.png)

Or is there any other way that I can put these two pictures on the same picture？

Thank you very much!

**Comment by zcang** [comment]
Hi, the current version on Github should work now.
